all:
	go build -o ../../bin/frontend frontend.go
	go build -o ../../bin/main main.go
	go build -o ../../bin/parser parser.go
	go build -o ../../bin/rebuild rebuild.go
	go build -o ../../bin/run_filters run_filters.go
	go build -o ../../bin/sent_mail sent_mail.go
	go build -o ../../bin/sqlite3 sqlite3.go
	go build -o ../../bin/yml yml.go
